name: Linux

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        ./clean.sh
        ./build.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: bin-linux
        path: bin

