name: Linux

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        echo "build start"
        pwd
        ls -al 
        chmod a+x clean.sh build.sh
        ./clean.sh
        ./build.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-linux
        path: dist

