name: Windows

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile
      run: |
        dir
        cl /Fe:sqinn.exe src\*.c
        dir
        .\sqinn.exe
        md dist
        copy sqinn.exe dist

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-windows
        path: dist

